# Generated by Django 5.0.2 on 2025-06-10 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="vehicle",
            options={"ordering": ["-created_at"]},
        ),
    ]
